USE [master]
GO
/****** Object:  Database [saep_db]    Script Date: 01/12/2023 20:56:24 ******/
CREATE DATABASE [saep_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'saep_db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\saep_db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'saep_db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\saep_db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [saep_db] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [saep_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [saep_db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [saep_db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [saep_db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [saep_db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [saep_db] SET ARITHABORT OFF 
GO
ALTER DATABASE [saep_db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [saep_db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [saep_db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [saep_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [saep_db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [saep_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [saep_db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [saep_db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [saep_db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [saep_db] SET  DISABLE_BROKER 
GO
ALTER DATABASE [saep_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [saep_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [saep_db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [saep_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [saep_db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [saep_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [saep_db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [saep_db] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [saep_db] SET  MULTI_USER 
GO
ALTER DATABASE [saep_db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [saep_db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [saep_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [saep_db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [saep_db] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [saep_db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [saep_db] SET QUERY_STORE = OFF
GO
USE [saep_db]
GO
/****** Object:  Table [dbo].[Atividade]    Script Date: 01/12/2023 20:56:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Atividade](
	[ID_Atividade] [int] identity NOT NULL,
	[Descricao_Atividade] [varchar](200) NOT NULL,
	[Turma_ID] [int] NOT NULL,
 CONSTRAINT [PK_Atividade] PRIMARY KEY CLUSTERED 
(
	[ID_Atividade] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Professores]    Script Date: 01/12/2023 20:56:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Professores](
	[ID_Professor] [int] identity NOT NULL,
	[nome] [varchar](200) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[senha] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Professores] PRIMARY KEY CLUSTERED 
(
	[ID_Professor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Turmas]    Script Date: 01/12/2023 20:56:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Turmas](
	[ID_Turmas] [int] identity NOT NULL,
	[Nome_turma] [varchar](100) NOT NULL,
	[Professor_ID] [int] NOT NULL,
 CONSTRAINT [PK_Turmas] PRIMARY KEY CLUSTERED 
(
	[ID_Turmas] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Atividade]  WITH CHECK ADD  CONSTRAINT [FK_Atividade_Turmas] FOREIGN KEY([Turma_ID])
REFERENCES [dbo].[Turmas] ([ID_Turmas])
GO
ALTER TABLE [dbo].[Atividade] CHECK CONSTRAINT [FK_Atividade_Turmas]
GO
ALTER TABLE [dbo].[Turmas]  WITH CHECK ADD  CONSTRAINT [FK_Turmas_Professores] FOREIGN KEY([Professor_ID])
REFERENCES [dbo].[Professores] ([ID_Professor])
GO
ALTER TABLE [dbo].[Turmas] CHECK CONSTRAINT [FK_Turmas_Professores]
GO
USE [master]
GO
ALTER DATABASE [saep_db] SET  READ_WRITE 
GO
